<a href="https://colab.research.google.com/github/cabbi120101/final_multi/blob/main/Try/%EC%B1%94%ED%94%84_%EC%9E%90%EC%97%B0%EC%96%B4%EC%B2%98%EB%A6%AC%EB%A5%BC%ED%95%B4%EB%B3%B4%EC%9E%90!.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import warnings; warnings.filterwarnings('ignore')

In [2]:
champ_info = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/동욱코드모음/마지막프로젝트/3주차/시도/champ_addSk.csv")
champ_info.head()

Unnamed: 0  ...                                             skillR
0           0  ...  {'id': 'AatroxR', 'name': 'World Ender', 'desc...
1           1  ...  {'id': 'AhriTumble', 'name': 'Spirit Rush', 'd...
2           2  ...  {'id': 'AkaliR', 'name': 'Perfect Execution', ...
3           3  ...  {'id': 'AkshanR', 'name': 'Comeuppance', 'desc...
4           4  ...  {'id': 'FerociousHowl', 'name': 'Unbreakable W...

[5 rows x 47 columns]

In [3]:
champ_info['skillQ'][0]

"{'id': 'AatroxQ', 'name': 'The Darkin Blade', 'description': 'Aatrox slams his greatsword down, dealing physical damage. He can swing three times, each with a different area of effect.', 'tooltip': 'Aatrox slams his greatsword, dealing {{ qdamage }} physical damage. If they are hit on the edge, they are briefly Knocked Up and they take {{ qedgedamage }} instead. This Ability can be Recast twice, each one changing shape and dealing 25% more damage than the previous one.', 'leveltip': {'label': ['Cooldown', 'Damage', 'Total AD Ratio'], 'effect': ['{{ cooldown }} -> {{ cooldownNL }}', '{{ qbasedamage }} -> {{ qbasedamageNL }}', '{{ qtotaladratio*100.000000 }}% -> {{ qtotaladrationl*100.000000 }}%']}, 'maxrank': 5, 'cooldown': [14, 12, 10, 8, 6], 'cooldownBurn': '14/12/10/8/6', 'cost': [0, 0, 0, 0, 0], 'costBurn': '0', 'datavalues': {}, 'effect': [None, [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [

In [4]:
from ast import literal_eval

champ_info['skillQ'] = champ_info['skillQ'].apply(literal_eval)
champ_info['skillW'] = champ_info['skillW'].apply(literal_eval)
champ_info['skillE'] = champ_info['skillE'].apply(literal_eval)
champ_info['skillR'] = champ_info['skillR'].apply(literal_eval)

In [5]:
champ_info['skillQ'][0]['description']

'Aatrox slams his greatsword down, dealing physical damage. He can swing three times, each with a different area of effect.'

In [6]:
champ_q = []
for i in range(len(champ_info)):
    champ_q.append(champ_info['skillQ'][i]['description'])

In [7]:
champ_w = []
for i in range(len(champ_info)):
    champ_w.append(champ_info['skillW'][i]['description'])

In [8]:
champ_e = []
for i in range(len(champ_info)):
    champ_e.append(champ_info['skillE'][i]['description'])

In [9]:
champ_r = []
for i in range(len(champ_info)):
    champ_r.append(champ_info['skillR'][i]['description'])

In [10]:
champ_summ = champ_info[['id','key','tags']]

In [11]:
champ_summ['champ_q'] = champ_q
champ_summ['champ_w'] = champ_w
champ_summ['champ_e'] = champ_e
champ_summ['champ_r'] = champ_r
champ_summ['champ_all_skill'] = champ_summ['champ_q']+champ_summ['champ_w']+champ_summ['champ_e']+champ_summ['champ_r']

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
champ_tips = champ_info[['key','allytips','enemytips']]

In [14]:
champ_tips['allytips'] = champ_tips['allytips'].apply(literal_eval)
champ_tips['enemytips'] = champ_tips['enemytips'].apply(literal_eval)

In [15]:
champ_tips['all_tips'] = champ_tips['enemytips'] + champ_tips['allytips']

In [16]:
champ_summ['all_tips'] = champ_tips['all_tips']

In [26]:
champ_summ['all_tips_literal'] = champ_summ['all_tips'].apply(lambda x : (' ').join(x))

In [28]:
champ_summ['all_discribtion'] = champ_summ['all_tips_literal'] + champ_summ['champ_all_skill']

In [24]:
champ_summ['champ_all_skill'] 

0      Aatrox slams his greatsword down, dealing phys...
1      Ahri sends out and pulls back her orb, dealing...
2      Akali throws out five kunai, dealing damage ba...
3      Akshan throws a boomerang that deals damage go...
4      Alistar smashes the ground, dealing damage to ...
                             ...                        
151    Zed and his shadows throw their shurikens.Each...
152    Ziggs throws a bouncing bomb that deals magic ...
153    Tosses a bomb to target area that sticks to un...
154    Zoe fires a missile that she can redirect in f...
155    Thick vines spread through the ground and expl...
Name: champ_all_skill, Length: 156, dtype: object

In [22]:
champ_summ['all_tips']

0      [Aatrox's attacks are very telegraphed, so use...
1      [Ahri's survivability is dramatically reduced ...
2      [Akali can still be hit by area effect spells ...
3      [Raising an eyebrow in the face of danger, Aks...
4      [Alistar is very disruptive but very tough - t...
                             ...                        
151    [Zed receives bonus effect from Attack Damage ...
152    [Don't step on Ziggs' mines! They'll slow you ...
153    [If you're able to match Zilean's speed, it ca...
154    [Zoe's Paddle Star deals more damage the furth...
155    [Zyra's seeds can be destroyed by stepping on ...
Name: all_tips, Length: 156, dtype: object

In [29]:
champ_summ.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   id                156 non-null    object
 1   key               156 non-null    int64 
 2   tags              156 non-null    object
 3   champ_q           156 non-null    object
 4   champ_w           156 non-null    object
 5   champ_e           156 non-null    object
 6   champ_r           156 non-null    object
 7   champ_all_skill   156 non-null    object
 8   all_tips          156 non-null    object
 9   all_tips_literal  156 non-null    object
 10  all_discribtion   156 non-null    object
dtypes: int64(1), object(10)
memory usage: 13.5+ KB


In [30]:
champ_summ['all_discribtion']

0      Aatrox's attacks are very telegraphed, so use ...
1      Ahri's survivability is dramatically reduced w...
2      Akali can still be hit by area effect spells w...
3      Raising an eyebrow in the face of danger, Aksh...
4      Alistar is very disruptive but very tough - tr...
                             ...                        
151    Zed receives bonus effect from Attack Damage i...
152    Don't step on Ziggs' mines! They'll slow you a...
153    If you're able to match Zilean's speed, it can...
154    Zoe's Paddle Star deals more damage the furthe...
155    Zyra's seeds can be destroyed by stepping on t...
Name: all_discribtion, Length: 156, dtype: object

## 1st Try - 자연어 처리 안하고 그냥 팁 + 스킬설명

In [36]:
count_vect = CountVectorizer(min_df=0, ngram_range=(1,2))
# ngram_range : 단어의 묶음
# ngram_range=(1,2) : 1개, 2개 단어 묶음 존재
all_discribtion_mat = count_vect.fit_transform(champ_summ['all_discribtion'])
print(all_discribtion_mat.shape)

(156, 21740)


In [105]:
from sklearn.metrics.pairwise import cosine_similarity

all_discribtion_sim = cosine_similarity(all_discribtion_mat, all_discribtion_mat)
print(all_discribtion_sim.shape)  # 유사도 행렬 크기
print(all_discribtion_sim[:2])    # 앞 2개만 출력

(156, 156)
[[1.         0.28759603 0.36180512 0.37021708 0.3773982  0.29195168
  0.35727112 0.34732854 0.26346765 0.35104646 0.32122127 0.42979843
  0.30623516 0.34742115 0.36386681 0.40773075 0.37999692 0.40512282
  0.26721392 0.35125519 0.29533144 0.39519544 0.38448027 0.37806789
  0.43920031 0.41396638 0.26112049 0.38228728 0.35672353 0.29986489
  0.42048037 0.37757614 0.31072476 0.31128851 0.32594352 0.35741113
  0.40980661 0.36299852 0.32201118 0.33960201 0.38899528 0.44179416
  0.27693079 0.28411529 0.35672414 0.37835104 0.27143935 0.40934447
  0.3706716  0.37996544 0.2119022  0.35722516 0.4060141  0.38503754
  0.27829777 0.37190064 0.30449577 0.35182472 0.36324514 0.35344889
  0.39148038 0.37086328 0.24381599 0.37142847 0.3795568  0.44862328
  0.24580586 0.38157683 0.27898602 0.32616816 0.37046126 0.37413501
  0.39956906 0.3155262  0.34702868 0.29936224 0.34466204 0.44263891
  0.34634826 0.34508552 0.35409485 0.38560105 0.31703109 0.34880495
  0.42319951 0.34379911 0.36360893 0.

In [106]:
all_discribtion_sim.argsort()[:, ::-1]

array([[  0,  65,  77, ...,  50,  92, 103],
       [  1,  52,  67, ...,   8,  68, 103],
       [  2,  67,  52, ...,  32,  68,   8],
       ...,
       [153,  25,  14, ..., 106,  92, 103],
       [154,  83,  16, ...,  92, 141, 103],
       [155,  65,  67, ...,   8, 103,  92]])

In [141]:
all_discribtion_sim_sorted_ind = np.sort(all_discribtion_sim, axis=1)[:,::-1]

print(all_discribtion_sim_sorted_ind[:1])

[[1.         0.44862328 0.44263891 0.44179416 0.43920031 0.43232446
  0.42979843 0.42465925 0.42319951 0.42048037 0.41738822 0.41396638
  0.40980661 0.40934447 0.40773075 0.4060141  0.40512282 0.4024735
  0.40086299 0.39969691 0.39956906 0.39880792 0.39591236 0.39519544
  0.39474041 0.39273994 0.39148038 0.38970448 0.38899528 0.38560105
  0.38503754 0.38448027 0.38402425 0.38228728 0.38157683 0.38141977
  0.38102785 0.38026581 0.37999692 0.37996544 0.3795568  0.37835104
  0.37806789 0.377577   0.37757614 0.3773982  0.37590759 0.37574313
  0.37466417 0.37413501 0.37290874 0.37261706 0.37190064 0.37142847
  0.37086328 0.3706716  0.37046126 0.37021708 0.36887572 0.36837416
  0.36654244 0.36621619 0.365749   0.36397201 0.36386681 0.36360893
  0.36324514 0.36299852 0.36180512 0.3584473  0.35812806 0.35741113
  0.35727112 0.35722516 0.35672414 0.35672353 0.35409485 0.35344889
  0.35182472 0.3517435  0.35125519 0.35104646 0.35076716 0.34880495
  0.34742443 0.34742115 0.34732854 0.34702868 0.3

In [115]:
# 높은 순으로 정렬된(내림차순 정렬된) 비교 행 위치 인덱스 값 구해서
# 첫 번째(0번 레코드)의 비교 행 위치 인덱스 값만 샘플로 추출
all_discribtion_sorted_ind = all_discribtion_sim.argsort()[:, ::-1]
print(all_discribtion_sorted_ind[:1]) # [0]

[[  0  65  77  41  24 112  11  98  84  30 125  25  36  47  15  52  17  88
  122 140  72 148 108  21 135  91  60 139  40  81  53  22  89  27  67  99
  118 111  16  49  64  45  23 133  31   4 120 102  87  71  93 101  55  63
   61  48  70   3 132  95 117 126 124 153  14  86  58  37   2 145 136  35
    6  51  44  28  80  59  57 150  19   9 129  83 155  13   7  74 116  78
   79  76  85  39 128 152 107 114 144 134 110 154 137 146  96  69  34  38
   10 143 151  82 142  73 127  33  90  32 109  94 131  12  56 130  29  75
  115  20   5 123   1 147 104  43 149 119  68  54  42 113  46 138  18 141
  121   8 100  97  26  66  62 105 106  50  92 103]]


In [63]:
# all_discribtion_sim_sorted_ind = all_discribtion_sim[all_discribtion_sim.argsort()[:, ::-1]]

In [142]:
# all_discribtion_sim[all_discribtion_sim.argsort()[:, ::-1]]

In [143]:
# all_discribtion_sim_sorted_ind[:1]

In [144]:
all_discribtion_sim_sorted_ind.shape

(156, 156)

In [145]:
all_discribtion_sim.shape

(156, 156)

In [146]:
# all_discribtion_sim[0]

In [147]:
# all_discribtion_sim_sorted_ind

In [68]:
# def find_sim_with_all_discribtion(df, sorted_ind, champ_name, top_n=10):
#     # titile 데이터 추출
#     champ_find = df[df['id'] == champ_name]
    
#     # title_name에 해당되는 데이터프레임 index 객체를 배열로 반환하고
#     # 유사도 순으로 top_n개의 index 추출
#     champ_index = champ_find.index.values
#     similar_indexes = sorted_ind[champ_index, :(top_n)]
    
#     # 추출된 top_n index 출력 
#     # 2차원 데이터를 1차원 array로 변환
#     print(similar_indexes)
#     similar_indexes_tips = similar_indexes.reshape(-1)
    
#     # index에 해당되는 데이터프레임 반환
#     return df.loc[similar_indexes]

### 1st Try 함수 부분

In [148]:
def find_sim_with_all_discribtion(df, sorted_ind, champ_name, top_n=10):
    # titile 데이터 추출
    champ_skill = df[df['id'] == champ_name]
    
    # title_name에 해당되는 데이터프레임 index 객체를 배열로 반환하고
    # 유사도 순으로 top_n개의 index 추출
    champ_index = champ_skill.index.values
    similar_indexes = sorted_ind[champ_index, :(top_n)]
    print(all_discribtion_sim_sorted_ind[champ_index, :(top_n)])
    # 추출된 top_n index 출력 
    # 2차원 데이터를 1차원 array로 변환
    print(similar_indexes)
    similar_indexes = similar_indexes.reshape(-1)
    
    # index에 해당되는 데이터프레임 반환
    return df.loc[similar_indexes][['id', 'tags']]

In [73]:
champ_skill = champ_summ[champ_summ['id'] == 'Zed']

In [75]:
champ_skill

id  ...                                    all_discribtion
151  Zed  ...  Zed receives bonus effect from Attack Damage i...

[1 rows x 11 columns]

In [76]:
champ_index = champ_skill.index.values

In [77]:
champ_index

array([151])

In [80]:
similar_indexes = all_discribtion_sorted_ind[champ_index, :10]

In [81]:
similar_indexes

array([[151,  25,  98,  24, 108,  36, 118,  21, 145, 114]])

In [82]:
 similar_indexes = similar_indexes.reshape(-1)

In [83]:
 similar_indexes

array([151,  25,  98,  24, 108,  36, 118,  21, 145, 114])

In [87]:
champ_summ.loc[similar_indexes][['id', 'tags']]

id                     tags
151       Zed             ['Assassin']
25       Ekko  ['Assassin', 'Fighter']
98   Renekton      ['Fighter', 'Tank']
24    DrMundo      ['Fighter', 'Tank']
108     Shaco             ['Assassin']
36     Gragas      ['Fighter', 'Mage']
118     Sylas     ['Mage', 'Assassin']
21     Darius      ['Fighter', 'Tank']
145   XinZhao  ['Fighter', 'Assassin']
114   Skarner      ['Fighter', 'Tank']

### 1st Try 결과

In [149]:
similar_all_discribtion_champ = find_sim_with_all_discribtion(champ_summ,all_discribtion_sorted_ind, 'Zed', 10)
similar_all_discribtion_champ[['id', 'tags']]

[[1.         0.36947769 0.36226941 0.36045008 0.35584601 0.35117223
  0.35038825 0.34547008 0.34286385 0.34190286]]
[[151  25  98  24 108  36 118  21 145 114]]


id                     tags
151       Zed             ['Assassin']
25       Ekko  ['Assassin', 'Fighter']
98   Renekton      ['Fighter', 'Tank']
24    DrMundo      ['Fighter', 'Tank']
108     Shaco             ['Assassin']
36     Gragas      ['Fighter', 'Mage']
118     Sylas     ['Mage', 'Assassin']
21     Darius      ['Fighter', 'Tank']
145   XinZhao  ['Fighter', 'Assassin']
114   Skarner      ['Fighter', 'Tank']